# Manual crosswalk between PAW MSA names and CBSA normalized names
# PAW uses older OMB MSA definitions, CBSA uses 2020+ definitions

PAW_TO_CBSA = {
    # Major metros with different naming
    'atlanta-sandy_springs-marietta_ga': 'atlanta-sandy_springs-roswell_ga',
    'austin-round_rock_tx': 'austin-round_rock-san_marcos_tx',
    'baltimore-towson_md': 'baltimore-columbia-towson_md',
    'birmingham-hoover_al': 'birmingham_al',
    'bloomington-normal_il': 'bloomington_il',
    'boise_city-nampa_id': 'boise_city_id',
    'boston-cambridge-quincy_ma-nh': 'boston-cambridge-newton_ma-nh',
    'bremerton-silverdale_wa': 'bremerton-silverdale-port_orchard_wa',
    'bridgeport-stamford-norwalk_ct': 'bridgeport-stamford-danbury_ct',
    'brunswick_ga': 'brunswick-st_simons_ga',
    'buffalo-niagara_falls_ny': 'buffalo-cheektowaga_ny',
    'cape_girardeau-jackson_mo-il': 'cape_girardeau_mo-il',
    'charlotte-gastonia-rock_hill_nc-sc': 'charlotte-concord-gastonia_nc-sc',
    'chicago-joliet-naperville_il-in-wi': 'chicago-naperville-elgin_il-in',
    'cincinnati-middletown_oh-ky-in': 'cincinnati_oh-ky-in',
    'cleveland-elyria-mentor_oh': 'cleveland-elyria_oh',
    'dayton_oh': 'dayton-kettering-beavercreek_oh',
    'denver-aurora-broomfield_co': 'denver-aurora-centennial_co',
    'detroit-warren-livonia_mi': 'detroit-warren-dearborn_mi',
    'evansville_in-ky': 'evansville_in',
    'fairbanks_ak': 'fairbanks-college_ak',
    'fayetteville-springdale-rogers_ar-mo': 'fayetteville-springdale-rogers_ar',
    'grand_rapids-wyoming_mi': 'grand_rapids-kentwood_mi',
    'greenville-mauldin-easley_sc': 'greenville-anderson_sc',
    'hinesville-fort_stewart_ga': 'hinesville_ga',
    'holland-grand_haven_mi': 'holland_mi',
    'honolulu_hi': 'urban_honolulu_hi',
    'houston-sugar_land-baytown_tx': 'houston-pasadena-the_woodlands_tx',
    'indianapolis-carmel_in': 'indianapolis-carmel-greenwood_in',
    'janesville_wi': 'janesville-beloit_wi',
    'joplin_mo': 'joplin_mo-ks',
    'kankakee-bradley_il': 'kankakee_il',
    'kennewick-pasco-richland_wa': 'kennewick-richland_wa',
    'killeen-temple-fort_hood_tx': 'killeen-temple_tx',
    'kingsport-bristol-bristol_tn-va': 'kingsport-bristol_tn-va',
    'la_crosse_wi-mn': 'la_crosse-onalaska_wi-mn',
    'lafayette_in': 'lafayette-west_lafayette_in',
    'las_vegas-paradise_nv': 'las_vegas-henderson-north_las_vegas_nv',
    'longview_wa': 'longview_wa',
    'los_angeles-long_beach-santa_ana_ca': 'los_angeles-long_beach-anaheim_ca',
    'macon_ga': 'macon-bibb_county_ga',
    'mankato-north_mankato_mn': 'mankato_mn',
    'miami-fort_lauderdale-pompano_beach_fl': 'miami-fort_lauderdale-west_palm_beach_fl',
    'milwaukee-waukesha-west_allis_wi': 'milwaukee-waukesha_wi',
    'minneapolis-st._paul-bloomington_mn-wi': 'minneapolis-st_paul-bloomington_mn-wi',
    'myrtle_beach-north_myrtle_beach-conway_sc': 'myrtle_beach-conway-north_myrtle_beach_sc',
    'new_haven-milford_ct': 'new_haven_ct',
    'new_orleans-metairie-kenner_la': 'new_orleans-metairie_la',
    'new_york-northern_new_jersey-long_island_ny-nj-pa': 'new_york-newark-jersey_city_ny-nj',
    'niles-benton_harbor_mi': 'niles_mi',
    'norwich-new_london_ct': 'norwich-new_london-willimantic_ct',
    'ocean_city_nj': 'ocean_city_nj',
    'ogden-clearfield_ut': 'ogden_ut',
    'olympia_wa': 'olympia-lacey-tumwater_wa',
    'omaha-council_bluffs_ne-ia': 'omaha_ne-ia',
    'palm_coast_fl': 'palm_coast-flagler_beach_fl',
    'panama_city-lynn_haven-panama_city_beach_fl': 'panama_city-panama_city_beach_fl',
    'parkersburg-marietta-vienna_wv-oh': 'parkersburg-vienna_wv',
    'phoenix-mesa-scottsdale_az': 'phoenix-mesa-chandler_az',
    'port_st._lucie_fl': 'port_st_lucie_fl',
    'portland-south_portland-biddeford_me': 'portland-south_portland_me',
    'poughkeepsie-newburgh-middletown_ny': 'kiryas_joel-poughkeepsie-newburgh_ny',
    'prescott_az': 'prescott_valley-prescott_az',
    'providence-new_bedford-fall_river_ri-ma': 'providence-warwick_ri-ma',
    'provo-orem_ut': 'provo-orem-lehi_ut',
    'racine_wi': 'racine-mount_pleasant_wi',
    'reno-sparks_nv': 'reno_nv',
    'sacramento--arden-arcade--roseville_ca': 'sacramento-roseville-folsom_ca',
    'saginaw-saginaw_township_north_mi': 'saginaw_mi',
    'salt_lake_city_ut': 'salt_lake_city-murray_ut',
    'san_diego-carlsbad-san_marcos_ca': 'san_diego-chula_vista-carlsbad_ca',
    'santa_barbara-santa_maria-goleta_ca': 'santa_maria-santa_barbara_ca',
    'sebastian-vero_beach_fl': 'sebastian-vero_beach-west_vero_corridor_fl',
    'sioux_falls_sd': 'sioux_falls_sd',
    'spokane_wa': 'spokane-spokane_valley_wa',
    'st._cloud_mn': 'st_cloud_mn',
    'st._george_ut': 'st_george_ut',
    'st._joseph_mo-ks': 'st_joseph_mo-ks',
    'st._louis_mo-il': 'st_louis_mo-il',
    'stockton_ca': 'stockton-lodi_ca',
    'tampa-st._petersburg-clearwater_fl': 'tampa-st_petersburg-clearwater_fl',
    'texarkana_tx-texarkana_ar': 'texarkana_tx-ar',
    'trenton-ewing_nj': 'trenton-princeton_nj',
    'vallejo-fairfield_ca': 'vallejo_ca',
    'vineland-millville-bridgeton_nj': 'vineland_nj',
    'virginia_beach-norfolk-newport_news_va-nc': 'virginia_beach-chesapeake-norfolk_va-nc',
    'visalia-porterville_ca': 'visalia_ca',
    'wenatchee_wa': 'wenatchee-east_wenatchee_wa',
    'youngstown-warren-boardman_oh-pa': 'youngstown-warren_oh',
    # Anderson - two different cities
    'anderson_in': 'anderson_in',
    'anderson_sc': 'anderson_sc',
    # These may not exist in CBSA - mark for manual review
    'madera_ca': 'madera_ca',
    'pascagoula_ms': 'pascagoula_ms',
}

# Reverse mapping: CBSA normalized name -> PAW name
CBSA_TO_PAW = {v: k for k, v in PAW_TO_CBSA.items()}
