#!/usr/bin/env python3
"""
Manual labels for Schoenmueller brand matching validation.
Labels generated by Claude reviewing brand name pairs.

TRUE = Same company/brand (match)
FALSE = Different companies (no match)
"""

MANUAL_LABELS = {
    # ===== TRUE MATCHES (same brand, different spelling/format) =====
    ('Macys', "Macey's"): True,  # Same brand, apostrophe difference
    ('Daveandbusters', "Dave & Buster's"): True,
    ('Tiffanyandco', 'Tiffany & Co.'): True,
    ('Aeropostale', 'Aéropostale'): True,  # Accent difference
    ('Stopandshop', 'Stop & Shop'): True,
    ('Barneysny', 'Barneys New York'): True,
    ('Hancockwhitney', 'Hancock and Whitney Bank'): True,
    ('Rollsroyce', 'Rolls‑Royce Motor Cars'): True,
    ('Bergdorfs', 'Bergdorf Goodman'): True,
    ('Ashleyhomestore', 'Ashley Furniture HomeStore'): True,
    ('Raymourflanigan', 'Raymour and Flanigan Furniture'): True,
    ('Pfchangs', "P.F. Chang's China Bistro"): True,
    ('Traderjoeslist', "Trader Joe's Distribution"): True,
    ('Astonmartin', 'Aston Martin,Cadillac'): True,  # Multi-brand dealer
    ('Infinitiusa', 'Infiniti,Subaru'): True,  # Multi-brand dealer
    ('Nissanusa', 'Nissan,Subaru'): True,  # Multi-brand dealer
    ('Subaru_Usa', 'Subaru,Lexus'): True,  # Multi-brand dealer
    ('Landroverusa', 'Land Rover,Jaguar'): True,  # Same parent company
    ('Lincolnmotorco', 'Lincoln,Hyundai Motor'): True,  # Multi-brand dealer
    ('Volvocars', 'Volvo Trucks'): True,  # Same parent
    ('Keybankctr', 'KeyBank ATM'): True,  # Same bank
    ('Santanderbankus', 'Santander Bank ATM'): True,  # Same bank
    ('Easternmntn', 'Eastern Mountain Sports'): True,
    ('Universalpics', 'Universal Studios'): True,
    ('Cambria_Hotels', 'Cambria Suites'): True,  # Same hotel brand
    ('Dollarcars', 'Dollar Rent A Car'): True,
    ('Restohardware', 'Restoration Hardware'): True,
    ('Tdbank_Us', 'TD Bank ATM'): True,
    ('Trumpgolf', 'TRUMP Hotels'): True,  # Same Trump org
    ('Mo_Hotels', 'Moxy Hotels'): True,  # Marriott brand
    ('Golf_Com', 'GolfTec'): False,  # Golf.com website vs GolfTec lessons - different
    ('Alofthotels', 'Arlo Hotels'): False,  # Different hotel chains
    ('Quickenloans', 'Quik-Lend Cash'): False,  # Different lenders

    # ===== FALSE MATCHES (different companies) =====
    ('Citibank', 'CIT Bank'): False,  # Different banks
    ('Glassdoor', 'Glass Doctor'): False,  # Job site vs glass repair
    ('Ponds', 'PODS'): False,  # Cosmetics vs storage
    ('Pelicansnba', 'Pelicana'): False,  # NBA team vs chicken
    ('Pelicansnba', "Pelican's SnoBalls"): False,  # NBA team vs snowballs
    ('Citizensbank', 'Citizens Trust Bank'): False,  # Different banks
    ('Citizensbank', 'Citizens and Farmers Bank'): False,
    ('Citizensbank', 'Citizens Community Bank Idaho'): False,
    ('Philips', 'Phillips 66'): False,  # Electronics vs gas
    ('Philips', 'Phillips Seafood'): False,
    ('Accenture', 'AccentCare'): False,  # Consulting vs home care
    ('Bcg', 'BCBG'): False,  # Consulting vs fashion
    ('Martell', 'Marella'): False,  # Cognac vs fashion
    ('Spacex', 'Spaces'): False,  # Space company vs coworking
    ('Moneygram', 'Money Mart'): False,
    ('Marshalls', 'Marshall Rousso'): False,  # Retail vs different
    ('Marshalls', 'Marshall Medical'): False,
    ('Barneysny', "Barney's Beanery"): False,  # Department store vs restaurant
    ('Elizabetharden', 'Elizabeth Grady'): False,  # Cosmetics vs spa
    ('Washingtonpost', 'Washington Sports Club'): False,  # Newspaper vs gym
    ('Hugoboss', "Hugo's"): False,  # Fashion vs restaurant
    ('Aol', 'Arol'): False,  # Internet vs unknown
    ('Houstontexans', "Houston's"): False,  # NFL team vs restaurant
    ('Houstonrockets', "Houston's"): False,  # NBA team vs restaurant
    ('Bose', 'Bosley'): False,  # Audio vs hair restoration
    ('Friendlys', 'Friendly Express'): False,  # Ice cream vs convenience
    ('Friendlys', 'Friendly Mart Food Stores'): False,
    ('Amstandard', 'Amstar'): False,  # American Standard vs different
    ('Dominos', 'Domino C-Store'): False,  # Pizza vs convenience
    ('Sharphomeusa', "Sharpe's"): False,  # Electronics vs unknown
    ('Burgerking', 'Burgerim'): False,  # Different burger chains
    ('Burgerking', 'BurgerFi'): False,
    ('Burgerking', 'Burger Monger'): False,
    ('Fidelity', 'Fidelitone'): False,  # Financial vs different
    ('Activia', 'Alcivia'): False,  # Yogurt vs agriculture
    ('Brooksbrothers', 'Brookshire Brothers'): False,  # Fashion vs grocery
    ('Audible_Com', 'Audibel'): False,  # Amazon audiobooks vs hearing aids
    ('Priceline', 'PriceRite'): False,  # Travel vs grocery
    ('Snopes', 'SNIPES'): False,  # Fact-check vs sneakers
    ('Sandisk', 'Sandri'): False,  # Storage vs unknown
    ('Citibank', 'Citizens Bank'): False,  # Different banks
    ('Williamssonoma', 'Williams Foods'): False,  # Kitchenware vs food
    ('Staplesstores', 'Staples Studio'): False,  # Office supplies vs different
    ('Burtsbees', 'Busy Bees'): False,  # Beauty vs childcare
    ('Pioneerusa', 'Pioneer Bank'): False,  # Electronics vs bank
    ('Pioneerusa', 'Pioneer Supermarkets'): False,
    ('Millerlite', 'Miller Paint'): False,  # Beer vs paint
    ('Kickstarter', 'Kicks Karate'): False,  # Crowdfunding vs martial arts
    ('Harpers', "Sharpe's"): False,  # Magazine vs unknown
    ('Chevron', 'Chevrolet'): False,  # Gas vs cars
    ('Carlsberg', "Carl's Jr."): False,  # Beer vs fast food
    ('Michaelkors', 'Michaels Stores'): False,  # Fashion vs crafts
    ('Michaelsstores', 'Michael Kors'): False,  # Crafts vs fashion
    ('Amazonfashion', 'Amazon Fresh'): False,  # Fashion vs grocery (both Amazon but different)
    ('Amazonfashion', 'Amazon Go'): False,
    ('Amazonpay', 'Amazon Go'): False,  # Payment vs store
    ('Russell_Invest', 'Russell Stover'): False,  # Investment vs candy
    ('Russell_Invest', "Russell's Convenience Stores"): False,
    ('Giants', 'Giant Fitness'): False,  # Sports team vs gym
    ('Brooklynnets', 'Brooklyn Fare'): False,  # NBA team vs grocery
    ('Brooklynnets', 'Brooklyn Boulders'): False,  # NBA team vs climbing
    ('Brooklynnets', 'Brooklyn Water Bagels'): False,
    ('Lifetimetv', 'Lifetime Fitness'): False,  # TV channel vs gym
    ('Redstate', 'Redstone'): False,  # Political blog vs unknown
    ('Evernote', 'Everlane'): False,  # Note app vs fashion
    ('Arco', 'Ayerco'): False,  # Gas station vs unknown
    ('Adroll', 'Arol'): False,  # Ad tech vs unknown
    ('Merrilledge', 'Merrell'): False,  # Financial vs shoes
    ('Freshdirect', 'Fresh City'): False,  # Delivery vs restaurant
    ('Dollartree', 'Dollar General'): False,  # Competitors
    ('Dollargeneral', 'Dollar Tree'): False,  # Competitors
    ('Dollartree', 'Dollar Castle'): False,
    ('Dollarcars', 'Dollar Castle'): False,  # Rental vs unknown
    ('Compassion', 'Compassus'): False,  # Charity vs hospice
    ('Compassion', 'Compass Coffee'): False,
    ('Travelzoo', 'Travelodge'): False,  # Deals vs hotels
    ('Automatic', 'AutoNation'): False,  # Different companies
    ('Championusa', 'Champion Car Wash'): False,  # Athletic wear vs car wash
    ('Bostonmarket', 'Best Market'): False,  # Restaurant vs grocery
    ('Newyorker', 'New York New York Pizza'): False,  # Magazine vs pizza
    ('Newyorker', 'New York Pilates'): False,
    ('Newyorker', 'New York Life Insurance'): False,
    ('Kohler', "Kohl's"): False,  # Plumbing vs retail
    ('Marmot', 'Marmi'): False,  # Outdoor gear vs unknown
    ('Bebe_Stores', 'BellStores'): False,  # Fashion vs convenience
    ('Discovery', 'Discover Vision'): False,  # TV channel vs eye care
    ('Cinemax', 'Cinema Cafe'): False,  # Premium cable vs theater
    ('Chroniclesu', 'Cronies'): False,  # Newspaper vs sports bar
    ('Acehotel', 'AC Hotel'): False,  # Different hotel chains (Ace vs Marriott AC)
    ('Haierappliances', 'Howards Appliances'): False,  # Manufacturer vs retailer
    ('Petsmart', 'Pet Supermarket'): False,  # Competitors
    ('Express', 'Exxpress Mart'): False,  # Fashion vs convenience
    ('Champssports', 'Champps'): False,  # Sports retail vs restaurant
    ('Dickies', "Dick's Drive-in"): False,  # Workwear vs restaurant
    ('Kitchenaidusa', 'Kitchen United'): False,  # Appliances vs ghost kitchen
    ('Clevelandgolf', 'Cleveland Clinic'): False,  # Golf vs hospital
    ('Speedway', 'Speedy Cafe'): False,  # Gas station vs cafe
    ('Volvocars', 'Volvo,Porsche'): False,  # Car brand vs multi-brand
    ('Packers', 'PACK-RAT'): False,  # NFL team vs storage
    ('Saints', 'Saint Alphonsus'): False,  # NFL team vs hospital
    ('Wildturkey', 'Wild by Nature'): False,  # Bourbon vs grocery
    ('American_Heart', 'American Home Fitness'): False,  # Charity vs fitness
    ('Columbiacrest', 'Columbia Sportswear'): False,  # Wine vs clothing
    ('Johnniewalkerus', 'Johnny Was'): False,  # Whisky vs fashion
    ('Cavs', 'CAVA'): False,  # NBA team vs restaurant
    ('Peta', "Pet's Barn"): False,  # Animal rights vs pet store
    ('Usatoday', 'USAA'): False,  # Newspaper vs insurance
    ('Pizzahut', 'Pizza Guys'): False,  # Different pizza chains
    ('Tacobell', 'Taco Bueno'): False,  # Different taco chains
    ('Tacobell', 'Taco Villa'): False,
    ('Papajohns', 'Papa Romanos'): False,  # Different pizza chains
    ('Papajohns', "Papa Gino's"): False,
    ('Absolutus', 'Absolut Care'): False,  # Vodka vs care
    ('Charlesschwab', "Charley's"): False,  # Financial vs restaurant
    ('Trex_Company', 'Trexcon'): False,  # Decking vs construction

    # Additional labels from second review pass
    ('Usagov', 'USA2GO'): False,  # Government vs convenience
    ('Freshdirect', 'Fresh&co.'): False,  # Delivery vs restaurant
    ('Morganshotels', 'Maldron Hotels'): False,  # Different hotel chains
    ('Brooklynnets', 'Brooklyn Bedding'): False,  # NBA vs mattress
    ('Dollarcars', 'Dollar Bank'): False,  # Rental vs bank
    ('Cnn', "Conn's"): False,  # News vs furniture
    ('Giantfoodstores', 'Giant Fitness'): False,  # Grocery vs gym
    ('Giants', 'GIANT Food Stores'): False,  # Sports team vs grocery
    ('Giants', 'Giant Food'): False,
    ('Zynga', 'Zinga'): False,  # Gaming vs different
    ('Bebe_Stores', "Bob's Stores"): False,  # Fashion vs discount
    ('Habitat_Org', 'Habitat for Humanity'): True,  # Same org
    ('Dollarcars', 'Dollar Tree'): False,  # Rental vs retail
    ('Victoriassecret', 'Victra'): False,  # Lingerie vs phone store
    ('Renhotels', 'Prince Hotels'): False,  # Different hotel chains
    ('Staplesstores', 'Stage Stores'): False,  # Office vs department
    ('Nature_Org', 'Natura'): False,  # Conservation vs cosmetics
    ('Eagles', 'EagleBank'): False,  # NFL team vs bank
    ('Livingsocial', 'Living Spaces'): False,  # Deals vs furniture
    ('Tradeadmis', 'Tradewinds Markets'): False,  # Unknown vs grocery
    ('Libertyvideos', 'Liberty Travel'): False,  # Videos vs travel
    ('Aaronsco', 'Arona Co'): False,  # Different rental companies
    ('Childrensplace', "Children's Orchard"): False,  # Kids clothes vs consignment
    ('Michaelsstores', 'Michaels Jewelers'): False,  # Crafts vs jewelry
    ('Infinitiusa', 'Infiniti,Cadillac'): True,  # Multi-brand dealer
    ('Realclearnews', 'Real Deals'): False,  # News vs stores
    ('Landroverusa', 'Land Rover,Audi,Jaguar,Porsche'): True,  # Multi-brand dealer
    ('Roche', 'RocOne'): False,  # Pharma vs unknown
    ('Trutv', 'Truist'): False,  # TV channel vs bank
    ('Southerncomfort', 'SouthernCarlson'): False,  # Whiskey vs unknown

    # More sports teams (all FALSE - teams vs unrelated businesses)
    ('Redsox', 'Red Robin'): False,
    ('Yankees', 'Yankee Candle'): False,
    ('Ravens', 'Raven Industries'): False,
    ('Steelers', 'Steel Fitness'): False,
    ('Bears', 'Bear Creek'): False,
    ('Patriots', 'Patrick Dealer Group'): False,
    ('Chiefs', 'Chief Supermarkets'): False,
    ('Raiders', 'Trader Vics'): False,
    ('Chargers', 'Chargepoint'): False,
    ('Falcons', 'Falcon Transport'): False,
    ('Panthers', 'Panther Premium'): False,
    ('Dolphins', 'Dolphin Fitness'): False,
    ('Bills', 'Bill Miller Bar-B-Q'): False,
    ('Jaguars', 'Jaguar'): False,  # NFL team vs car brand
    ('Titans', 'Titan Fitness'): False,
    ('Colts', 'Colton'): False,
    ('Texans', 'Texas Roadhouse'): False,

    # Media/tech companies (FALSE - no physical retail)
    ('Twitter', 'Sweet Frog'): False,
    ('Snapchat', 'Snap Fitness'): False,
    ('Spotify', 'Sport Clips'): False,
    ('Netflix', 'Pet Valu'): False,
    ('Pinterest', 'Interior Define'): False,
    ('Linkedin', 'Lincoln'): False,
    ('Slack', 'Slackers'): False,
    ('Dropbox', 'Drop Off Store'): False,
    ('Uber', 'Uber Eats'): True,  # Same company
    ('Lyft', 'Lift Brands'): False,
    ('Airbnb', 'Air Methods'): False,
    ('Venmo', 'Vemo'): False,
    ('Paypal', 'Payless'): False,
    ('Square', 'Square One'): False,
    ('Stripe', 'Striped Pig'): False,

    # More retail clarifications
    ('Nordstrom', 'Nordstrom Rack'): True,  # Same company
    ('Bloomingdales', "Bloomingdale's"): True,
    ('Neimanmarcus', 'Neiman Marcus'): True,
    ('Saksfifthavenue', 'Saks Fifth Avenue'): True,
    ('Barnesandnoble', 'Barnes & Noble'): True,
    ('Bedbathandbeyond', 'Bed Bath & Beyond'): True,
    ('Bathandbodyworks', 'Bath & Body Works'): True,
    ('Potterybarn', 'Pottery Barn'): True,
    ('Potterybarnkids', 'Pottery Barn Kids'): True,
    ('Westelm', 'West Elm'): True,
    ('Crateandbarrel', 'Crate & Barrel'): True,
    ('Cb2', 'CB2'): True,

    # More auto/dealer combinations that are TRUE
    ('Landroverusa', 'Land Rover,Jaguar,Lexus'): True,
    ('Landroverusa', 'Land Rover,Jaguar,Porsche'): True,
    ('Subaru_Usa', 'Subaru,Mazda'): True,
    ('Infinitiusa', 'Infiniti,Mazda'): True,
    ('Infinitiusa', 'Infiniti,Hyundai Motor'): True,
    ('Lincolnmotorco', 'Lincoln,Ford Motor Company'): True,
    ('Lincolnmotorco', 'Lincoln,Volvo'): True,
    ('Rollsroyce', 'Rolls‑Royce Motor Cars,Lamborghini'): True,
    ('Rollsroyce', 'Rolls‑Royce Motor Cars,Bentley Motors'): True,
    ('Rollsroyce', 'Rolls‑Royce Motor Cars,Aston Martin'): True,
}

if __name__ == '__main__':
    true_count = sum(1 for v in MANUAL_LABELS.values() if v)
    false_count = sum(1 for v in MANUAL_LABELS.values() if not v)
    print(f"Manual labels: {len(MANUAL_LABELS)} total")
    print(f"  TRUE matches: {true_count}")
    print(f"  FALSE matches: {false_count}")
